const dclFermentis: TYeast[] = [
  {
    'min-temperature': 15,
    name: 'K-97 SafAle German Ale',
    'max-temperature': 24,
    type: 'Ale',
    'best-for': 'High attenuation ales, wheat beers and weizens.',
    laboratory: 'DCL/Fermentis',
    attenuation: 0.765,
    notes:
      'Low sedimentation yeast, sometimes used in open fermentation. Good for wheat beers, weizens and light ales.',
    flocculation: 'Medium',
    form: 'Dry',
    'product-id': 'K-97',
  },
  {
    'min-temperature': 15,
    name: 'S-04 SafAle English Ale',
    'max-temperature': 24,
    type: 'Ale',
    'best-for': 'Great general purpose ale yeast.',
    laboratory: 'DCL/Fermentis',
    attenuation: 0.765,
    notes:
      'Fast starting, fast fermenting yeast. Quick attenuation helps to produce a clean, crisp, clear ale. Can be used in a wide range of ales.',
    flocculation: 'Medium',
    form: 'Dry',
    'product-id': 'S-04',
  },
  {
    'min-temperature': 8.89,
    name: 'S-189 SafLager German Lager',
    'max-temperature': 13.33,
    type: 'Lager',
    'best-for': 'Wide range of lagers and pilsners.',
    laboratory: 'DCL/Fermentis',
    attenuation: 0.765,
    notes:
      'Popular lager yeast strain. Produces wide range of continental lagers and pilsners. Clean finish.',
    flocculation: 'High',
    form: 'Dry',
    'product-id': 'S-189',
  },
  {
    'min-temperature': 7.78,
    name: 'S-23 SafLager West European Lager',
    'max-temperature': 10,
    type: 'Lager',
    'best-for': 'German style Lagers and Pilsners.',
    laboratory: 'DCL/Fermentis',
    attenuation: 0.765,
    notes:
      'German lager yeast strain. Performs well at low temperature. High flocculation and attenuation for a clean German finish.',
    flocculation: 'High',
    form: 'Dry',
    'product-id': 'S-23',
  },
  {
    'min-temperature': 18.33,
    name: 'S-33 SafBrew Ale',
    'max-temperature': 22.22,
    type: 'Ale',
    'best-for': 'Most ales.',
    laboratory: 'DCL/Fermentis',
    attenuation: 0.765,
    notes:
      'General purpose ale yeast, widely used. Very consistent, clean finish. High attenuation and good flavor profile.',
    flocculation: 'Medium',
    form: 'Dry',
    'product-id': 'S-33',
  },
  {
    'min-temperature': 15.56,
    name: 'T-58 SafBrew Specialty Ale',
    'max-temperature': 22.22,
    type: 'Ale',
    'best-for': 'Complex ales.',
    laboratory: 'DCL/Fermentis',
    attenuation: 0.765,
    notes:
      'Estery, somewhat spicy ale yeast. Solid yeast formation at end of fermentation. Widely used for bottle and cask conditioning.',
    flocculation: 'Medium',
    form: 'Dry',
    'product-id': 'T-58',
  },
  {
    'min-temperature': 15,
    name: 'US-05 Safale American',
    'max-temperature': 23.89,
    type: 'Ale',
    'best-for': 'American ale, other clean finish ales',
    laboratory: 'DCL/Fermentis',
    attenuation: 0.765,
    notes:
      'American ale yeast that produces well balanced beers with low diacetyl and a very clean, crisp end palate.',
    flocculation: 'Medium',
    form: 'Dry',
    'product-id': 'US-05',
  },
  {
    'min-temperature': 8.89,
    name: 'W-34/70 Saflager Lager',
    'max-temperature': 15,
    type: 'Lager',
    'best-for': 'European lagers',
    laboratory: 'DCL/Fermentis',
    attenuation: 0.765,
    notes:
      'A famous yeast strain from Weihenstephan Germany used worldwide in brewing. Their most popular strain for lagers.',
    flocculation: 'High',
    form: 'Dry',
    'product-id': 'W-34/70',
  },
  {
    'min-temperature': 15,
    name: 'WB-06 Safbrew Wheat',
    'max-temperature': 23.89,
    type: 'Wheat',
    'best-for': 'Wheat beers',
    laboratory: 'DCL/Fermentis',
    attenuation: 0.765,
    notes:
      'A specialty yeast for wheat beer fermentation. The yeast produces a subtle estery and phenlol flavor typical of wheat beers.',
    flocculation: 'Medium',
    form: 'Dry',
    'product-id': 'WB-06',
  },
];

export default dclFermentis;
