version: '3.1'
services:  
  mongo:
    container_name: ${MONGODB_DB}-mongodb
    image: mongo
    volumes:
    - ${MONGO_DATA_DIR}:/data/db
    logging:
      driver: none
    ports:
    - "27017:27017"
    
  app: 
    container_name: ${APP_NAME}
    depends_on:
      - mongo
    image: ${APP_NAME}:0.0.1
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: node dist/main.js
    ports: 
      - 4500:4500
    volumes:
      - .:/usr/app
      - /usr/app/node_modules 
    environment:
      MONGODOCKER: mongodb://${MONGODB_DB}-mongodb:27017/${MONGODB_DB}  
    restart: unless-stopped    


networks:
  default:
    external:
      name: ${NETWORK_NAME}