version: '3.1'
services:
  
  mongo:
    container_name: ${MONGODB_DB}-mongodb
    image: mongo
    volumes:
    - ${MONGO_DATA_DIR}:/data/db
    ports:
    - "27017:27017"

networks:
  default:
    external:
      name: ${NETWORK_NAME}