declare type TBjcp2015Categories =
  | 'Alternative Fermentables Beer'
  | 'Amber And Brown American Beer'
  | 'Amber Bitter European Beer'
  | 'Amber Malty European Lager'
  | 'American Porter And Stout'
  | 'American Wild Ale'
  | 'Belgian Ale'
  | 'British Bitter'
  | 'Brown British Beer'
  | 'Czech Lager'
  | 'Dark British Beer'
  | 'Dark European Lager'
  | 'European Sour Ale'
  | 'Fruit Beer'
  | 'German Wheat Beer'
  | 'Historical Beer'
  | 'International Lager'
  | 'Ipa'
  | 'Irish Beer'
  | 'Pale American Ale'
  | 'Pale Bitter European Beer'
  | 'Pale Commonwealth Beer'
  | 'Pale Malty European Lager'
  | 'Scottish Ale'
  | 'Smoked Beer'
  | 'Specialty Beer'
  | 'Spiced Beer'
  | 'Standard American Beer'
  | 'Strong American Ale'
  | 'Strong Belgian Ale'
  | 'Strong British Ale'
  | 'Strong European Beer'
  | 'Trappist Ale'
  | 'Wood Beer';
