const adjuncts: TFermentables[] = [
  {
    name: 'Barley Hulls',
    yield: 0.0,
    color: 0,
    'max-in-batch': 0.05,
    potential: 1.0,
    notes: 'Neutral hulls used to improve lautering.',
    'coarse-fine-diff': 0,
    moisture: 0.4,
    'diastatic-power': 0,
    protein: 0,
    'recommend-mash': false,
    'add-after-boil': false,
    type: 'Adjunct',
  },

  {
    name: 'Grits',
    yield: 0.8,
    color: 1,
    'max-in-batch': 0.1,
    potential: 1.037,
    notes: 'Imparts a corn and grain taste',
    'coarse-fine-diff': 0,
    moisture: 0.4,
    'diastatic-power': 0,
    protein: 0,
    'recommend-mash': true,
    'add-after-boil': false,
    type: 'Adjunct',
  },

  {
    name: 'Rice Hulls',
    yield: 0.0,
    color: 0,
    'max-in-batch': 0.05,
    potential: 1.0,
    notes: 'Neutral hulls used to improve lautering.',
    'coarse-fine-diff': 0,
    moisture: 0.4,
    'diastatic-power': 0,
    protein: 0,
    'recommend-mash': false,
    'add-after-boil': false,
    type: 'Adjunct',
  },
];

export default adjuncts;
