const extracts: TFermentables[] = [
  {
    name: 'Amber Liquid Extract',
    yield: 0.78,
    color: 13,
    'add-after-boil': false,
    'max-in-batch': 1.0,
    potential: 1.036,
    notes: 'Amber colored liquid malt extract for general purpose use.',
    'recommend-mash': false,
    type: 'Extract',
    'coarse-fine-diff': 0,
    moisture: 1,
    'diastatic-power': 0,
    protein: 1,
  },

  {
    name: 'Dark Liquid Extract',
    yield: 0.78,
    color: 18,
    'add-after-boil': false,
    'max-in-batch': 1.0,
    potential: 1.036,
    notes: 'For general-purpose use in darker beers.',
    'recommend-mash': false,
    type: 'Extract',
    'coarse-fine-diff': 0,
    moisture: 1,
    'diastatic-power': 0,
    protein: 1,
  },
  {
    name: 'Honey',
    yield: 0.75,
    color: 1,
    'add-after-boil': true,
    'max-in-batch': 0.3,
    potential: 1.035,
    notes:
      'Used for light flavor and body. Can be added to primary fermentation, but must be pasteurized',
    'recommend-mash': false,
    type: 'Extract',
    'coarse-fine-diff': 0,
    moisture: 1,
    'diastatic-power': 0,
    protein: 1,
  },

  {
    name: 'Pale Liquid Extract',
    yield: 0.78,
    color: 8,
    'add-after-boil': false,
    'max-in-batch': 1.0,
    potential: 1.036,
    notes: 'For general-purpose use in light and pale beers.',
    'recommend-mash': false,
    type: 'Extract',
    'coarse-fine-diff': 0,
    moisture: 1,
    'diastatic-power': 0,
    protein: 1,
  },

  {
    name: 'Pilsner Liquid Extract',
    yield: 0.78,
    color: 4,
    'add-after-boil': false,
    'max-in-batch': 1.0,
    potential: 1.036,
    notes: 'For general-purpose use in pale beers.',
    'recommend-mash': false,
    type: 'Extract',
    'coarse-fine-diff': 0,
    moisture: 1,
    'diastatic-power': 0,
    protein: 1,
  },

  {
    name: 'Rice Extract Syrup',
    yield: 0.69,
    color: 7,
    'add-after-boil': false,
    'max-in-batch': 0.15,
    potential: 1.032,
    notes: 'Used like other rice adjuncts in American and Japanese lagers.',
    'recommend-mash': false,
    type: 'Extract',
    'coarse-fine-diff': 0,
    moisture: 1,
    'diastatic-power': 0,
    protein: 1,
  },

  {
    name: 'Rye Liquid Extract',
    yield: 0.69,
    color: 7,
    'add-after-boil': false,
    'max-in-batch': 1.0,
    potential: 1.034,
    notes: 'Mixed rye/barley extract for general-purpose brewing.',
    'recommend-mash': false,
    type: 'Extract',
    'coarse-fine-diff': 0,
    moisture: 1,
    'diastatic-power': 0,
    protein: 1,
  },

  {
    name: 'Sorghum Syrup',
    yield: 0.78,
    color: 7,
    'add-after-boil': false,
    'max-in-batch': 1.0,
    potential: 1.036,
    notes:
      'A gluten-free extract based on sorghum grain. Can be used as a substitute for Light Malt Extract.',
    'recommend-mash': false,
    type: 'Extract',
    'coarse-fine-diff': 0,
    moisture: 1,
    'diastatic-power': 0,
    protein: 1,
  },

  {
    name: 'Wheat Liquid Extract',
    yield: 0.78,
    color: 8,
    'add-after-boil': false,
    'max-in-batch': 1.0,
    potential: 1.036,
    notes: 'Wheat/barley extract for general-purpose use in wheat beers.',
    'recommend-mash': false,
    type: 'Extract',
    'coarse-fine-diff': 0,
    moisture: 1,
    'diastatic-power': 0,
    protein: 1,
  },
];

export default extracts;
