const sugars: TFermentables[] = [
  {
    name: 'Dark Brown Sugar',
    color: 50,
    potential: 1.046,
    'max-in-batch': 0.1,
    yield: 1.0,
    notes: 'Imparts a sweet, rich flavor.',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Light Brown Sugar',
    color: 8,
    potential: 1.046,
    'max-in-batch': 0.1,
    yield: 1.0,
    notes: 'Imparts a sweet, rich flavor.',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Belgian Candi Syrup - 45L',
    potential: 1.032,
    yield: 0.783,
    color: 60,
    'max-in-batch': 0.2,
    notes:
      'Crystalized candi sugar for use in Tripels, Dubbels, and holiday ales',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Belgian Candi Syrup - 90L',
    yield: 0.783,
    potential: 1.032,
    color: 121,
    'max-in-batch': 0.2,
    notes:
      'Crystalized candi sugar for use in Tripels, Dubbels, and holiday ales',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Belgian Candi Syrup - 180L',
    potential: 1.032,
    yield: 0.783,
    color: 243,
    'max-in-batch': 0.2,
    notes:
      'Crystalized candi sugar for use in Tripels, Dubbels, and holiday ales',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Clear Candi Sugar',
    potential: 1.036,
    yield: 0.783,
    color: 1,
    'max-in-batch': 0.2,
    notes:
      'Crystalized candi sugar for use in Tripels, Dubbels, and holiday ales',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Cane Sugar',
    potential: 1.046,
    yield: 1.0,
    color: 0,
    'max-in-batch': 0.07,
    notes: 'Common, household sugat to lighten the flavor and body',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Beet Sugar',
    potential: 1.046,
    yield: 1.0,
    color: 0,
    'max-in-batch': 0.07,
    notes: 'Common, household sugat to lighten the flavor and body',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Corn Sugar',
    potential: 1.046,
    yield: 1.0,
    color: 0,
    'max-in-batch': 0.05,
    notes: 'Common bottling sugar',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },
  {
    name: 'Dextrose',
    potential: 1.046,
    yield: 1.0,
    color: 0,
    'max-in-batch': 0.05,
    notes: 'Common bottling sugar',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Corn Syrup',
    potential: 1.036,
    yield: 0.783,
    color: 0,
    'max-in-batch': 0.1,
    notes: 'Syrup derived from corn sugar',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Demerara Sugar',
    potential: 1.046,
    yield: 1.0,
    color: 2,
    'max-in-batch': 0.1,
    notes: 'A dark, unrefined sugar that contains molasses',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Invert Sugar',
    potential: 1.046,
    yield: 1.0,
    color: 0,
    'max-in-batch': 0.1,
    notes: 'A sugar used to increase starting gravity',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Milk Sugar',
    potential: 1.035,
    yield: 0.761,
    color: 0,
    'max-in-batch': 0.1,
    notes: 'A partially fermentable sugar that adds lasting sweetness',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Lactose',
    potential: 1.035,
    yield: 0.761,
    color: 0,
    'max-in-batch': 0.1,
    notes: 'A partially fermentable sugar that adds lasting sweetness',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Molasses',
    potential: 1.036,
    yield: 0.783,
    color: 80,
    'max-in-batch': 0.05,
    notes: 'A strong, dark, and sweet sugar',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Maple Syrup',
    potential: 1.03,
    yield: 0.652,
    color: 35,
    'max-in-batch': 0.1,
    notes:
      'If added during the boil it will add a dry, woodsy flavor. If added at bottling, the smooth maple flavor comes through',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Table Sugar',
    potential: 1.046,
    yield: 1.0,
    color: 1,
    'max-in-batch': 0.1,
    notes: 'A sugar used to increase starting gravity',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Sucrose',
    potential: 1.046,
    yield: 1.0,
    color: 1,
    'max-in-batch': 0.1,
    notes: 'A sugar used to increase starting gravity',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },

  {
    name: 'Turbinado',
    potential: 1.044,
    yield: 0.957,
    color: 10,
    'max-in-batch': 0.1,
    notes: 'A light, raw brown sugar used to increase starting gravity',
    type: 'Sugar',
    'recommend-mash': false,
    'add-after-boil': false,
    'coarse-fine-diff': 0,
    'diastatic-power': 0,
    moisture: 0.04,
    protein: 0,
  },
];

export default sugars;
